# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('ARCHIVED', 'Arquivado'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=20)),
                ('s3_path', models.CharField(blank=True, help_text='Prefixo S3 do projeto no Data Lake', max_length=500, verbose_name='Caminho S3')),
                ('glue_database', models.CharField(blank=True, max_length=255, verbose_name='Glue Database')),
                ('athena_workgroup', models.CharField(blank=True, max_length=255, verbose_name='Athena Workgroup')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('ANALYST', 'Analista'), ('APPROVER', 'Aprovador'), ('VIEWER', 'Visualizador')], default='VIEWER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
            options={
                'db_table': 'project_members',
                'ordering': ['project', 'role'],
            },
        ),
    ]
