# Generated by Django 4.2.16 on 2026-04-04 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Domínio')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Domínio')),
                ('icon', models.CharField(default='Database', help_text='Ícone Lucide', max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_domains', to=settings.AUTH_USER_MODEL, verbose_name='Dono do Domínio (Data Product Manager)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='users.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Domínio de Dados',
                'verbose_name_plural': 'Domínios de Dados',
                'db_table': 'data_domains',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.datadomain', verbose_name='Domínio de Dados'),
        ),
    ]
