# Generated by Django 4.2.16 on 2026-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_datadomain_project_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crawler_frequency',
            field=models.CharField(blank=True, max_length=100, verbose_name='Frequência do Crawler'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_confidentiality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Confidencialidade dos Dados'),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_data_owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domain Data Owner'),
        ),
        migrations.AddField(
            model_name='project',
            name='intake_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados de Intake'),
        ),
    ]
