# Generated by Django 4.2.16 on 2026-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_crawler_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis_max_rows',
            field=models.PositiveIntegerField(default=5000, help_text='Máximo de linhas processadas pelo Agente de Estatística (Pandas) para garantir performance.', verbose_name='Limite de Linhas para Análise IA'),
        ),
    ]
