# Generated by Django 4.2.16 on 2026-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_analysis_max_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_temperature',
            field=models.FloatField(default=0.3, help_text='Calibração do nível de criatividade da IA (0.0 a 1.0).', verbose_name='Temperatura da IA'),
        ),
    ]
