# Generated by Django 4.2.16 on 2026-04-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_lib', '0002_initial'),
        ('projects', '0006_project_ai_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specialist_prompt',
            field=models.ForeignKey(blank=True, help_text='Persona cognitiva selecionada para guiar as análises e o draft deste projeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='templates_lib.prompttemplate', verbose_name='Especialista de Domínio'),
        ),
    ]
