# Generated by Django 4.2.16 on 2026-04-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSystemPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('persona_title', models.CharField(default='Analista Financeiro Sênior', max_length=255, verbose_name='Título da Persona')),
                ('persona_description', models.TextField(default='Você é um analista financeiro sênior especializado em identificar relações ocultas em dados e gerar insights estratégicos.', verbose_name='Descrição da Persona')),
                ('style_guide', models.JSONField(blank=True, default=dict, help_text='Configuração de cores, logos (NTT DATA, AWS) e fontes padrão corporativas.', verbose_name='Guia de Estilo (JSON)')),
                ('compliance_rules', models.TextField(blank=True, help_text='Políticas de dados e segurança que a LLM deve observar.', verbose_name='Regras de Compliance')),
                ('language', models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_prompts', to='users.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'System Prompt Global',
                'verbose_name_plural': 'System Prompts Globais',
                'db_table': 'governance_system_prompts',
                'ordering': ['-created_at'],
            },
        ),
    ]
