# Generated by Django 4.2.16 on 2026-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsystemprompt',
            name='enable_anomaly_detection',
            field=models.BooleanField(default=False, help_text='Identifica e sinaliza outliers e picos no dataset (Beta).', verbose_name='Ativar Detecção de Anomalias'),
        ),
        migrations.AddField(
            model_name='globalsystemprompt',
            name='enable_correlation_profile',
            field=models.BooleanField(default=False, help_text='Gera estatísticas de correlação entre colunas categóricas e numéricas (Beta).', verbose_name='Ativar Perfil de Correlação'),
        ),
        migrations.AddField(
            model_name='globalsystemprompt',
            name='enable_temporal_profile',
            field=models.BooleanField(default=True, help_text='Gera estatísticas de tendências mensais/semanais na ingestão de dados.', verbose_name='Ativar Perfil Temporal'),
        ),
    ]
