# Generated by Django 4.2.16 on 2026-04-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_add_data_profiling_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsystemprompt',
            name='enable_clustering_profile',
            field=models.BooleanField(default=False, help_text='Agrupamento automático de perfis segmentados (Em breve).', verbose_name='Ativar Clustering'),
        ),
        migrations.AddField(
            model_name='globalsystemprompt',
            name='enable_forecasting_profile',
            field=models.BooleanField(default=False, help_text='Previsão preditiva baseada em séries temporais (Em breve).', verbose_name='Ativar Forecasting'),
        ),
        migrations.AddField(
            model_name='globalsystemprompt',
            name='max_tokens_limit',
            field=models.IntegerField(default=32000, help_text='Cota máxima de tokens para respostas da IA (Claude 3.5 Sonnet).', verbose_name='Limite de Tokens Master'),
        ),
    ]
