# Generated by Django 4.2.16 on 2026-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_globalsystemprompt_enable_clustering_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsystemprompt',
            name='ingestion_row_limit',
            field=models.IntegerField(default=5000, help_text='Número máximo de linhas processadas pelo Agent-BI durante a ingestão (Governança).', verbose_name='Limite de Linhas para Ingestão'),
        ),
    ]
