# Generated by Django 4.2.16 on 2026-04-10 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_globalsystemprompt_ingestion_row_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSystemPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agent_key', models.CharField(help_text='Ex: supervisor_agent, pandas_agent, nl2sql_agent', max_length=100, unique=True, verbose_name='Chave do Agente')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Agente')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Objetivo')),
                ('content', models.TextField(verbose_name='System Prompt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'System Prompt de Agente',
                'verbose_name_plural': 'System Prompts de Agentes',
                'db_table': 'governance_agent_prompts',
                'ordering': ['agent_key'],
            },
        ),
    ]
