# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financeiro'), ('SALES', 'Vendas'), ('MARKETING', 'Marketing'), ('OPERATIONS', 'Operações'), ('HR', 'RH'), ('EXECUTIVE', 'Executivo'), ('CUSTOM', 'Customizado')], default='CUSTOM', max_length=50)),
                ('html_template', models.TextField(blank=True, verbose_name='Template HTML Base')),
                ('prompt_hints', models.TextField(blank=True, help_text='Instruções específicas enviadas ao Generator para seguir este template', verbose_name='Dicas para o Generator Agent')),
                ('css_theme', models.TextField(blank=True, verbose_name='CSS do Tema')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('s3_path', models.CharField(blank=True, max_length=1000)),
                ('is_public', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'db_table': 'dashboard_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(verbose_name='Template do Prompt')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Variáveis interpoláveis: [{name, description, required}]')),
                ('is_public', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'db_table': 'prompt_templates',
                'ordering': ['category', 'name'],
            },
        ),
    ]
