# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20)),
                ('cloudfront_url', models.URLField(blank=True, verbose_name='URL CloudFront')),
                ('s3_published_path', models.CharField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações de layout, tema, filtros', verbose_name='Configuração')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('SUCCEEDED', 'Concluído'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('step_functions_execution_arn', models.CharField(blank=True, max_length=500)),
                ('step_functions_execution_name', models.CharField(blank=True, max_length=255)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('current_iteration', models.PositiveIntegerField(default=0)),
                ('max_iterations', models.PositiveIntegerField(default=3)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='dashboards.dashboard')),
            ],
            options={
                'db_table': 'generation_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
