# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(verbose_name='Instrução')),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False, help_text='Instrução disponível para todos os projetos do tenant')),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'instructions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('change_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'instruction_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
