# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructionversion',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='instructions.instruction'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instruction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='instructionversion',
            unique_together={('instruction', 'version_number')},
        ),
    ]
