# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0001_initial'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField(verbose_name='Número da Versão')),
                ('state', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CANDIDATE', 'Candidato'), ('UNDER_REVIEW', 'Em Revisão'), ('APPROVED', 'Aprovado'), ('BLUEPRINT', 'Blueprint'), ('ARCHIVED', 'Arquivado'), ('REJECTED', 'Rejeitado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('html_s3_path', models.CharField(blank=True, max_length=1000, verbose_name='Path HTML no S3')),
                ('html_preview_url', models.URLField(blank=True, verbose_name='URL Preview')),
                ('sql_queries', models.JSONField(blank=True, default=list, help_text='Lista de queries Athena geradas pela IA', verbose_name='Queries SQL')),
                ('ai_insights', models.TextField(blank=True, verbose_name='Insights IA')),
                ('full_prompt', models.TextField(blank=True, help_text='Prompt completo enviado à IA (para reprodutibilidade)', verbose_name='Prompt Completo')),
                ('ai_score', models.FloatField(blank=True, help_text='Score do Critic Agent (0.0 a 1.0)', null=True, verbose_name='Score IA')),
                ('critic_feedback', models.TextField(blank=True, verbose_name='Feedback do Critic')),
                ('iterations', models.PositiveIntegerField(default=1, verbose_name='Iterações IA')),
                ('instruction_snapshot', models.JSONField(blank=True, default=dict, help_text='Cópia da instrução usada na geração', verbose_name='Snapshot da Instrução')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do Template')),
                ('dataset_snapshot', models.JSONField(blank=True, default=dict, help_text='Schema e metadata do dataset no momento da geração', verbose_name='Snapshot do Dataset')),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True, verbose_name='Resumo de Mudanças')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dashboards.dashboard', verbose_name='Dashboard')),
                ('infra_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='infra.infraconfig', verbose_name='Config Infra')),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
                'db_table': 'versions',
                'ordering': ['-version_number'],
                'unique_together': {('dashboard', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='VersionIterationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('iteration_number', models.PositiveIntegerField()),
                ('generator_prompt', models.TextField(blank=True)),
                ('generator_response', models.TextField(blank=True)),
                ('critic_prompt', models.TextField(blank=True)),
                ('critic_response', models.TextField(blank=True)),
                ('score', models.FloatField(null=True)),
                ('feedback', models.TextField(blank=True)),
                ('execution_time_seconds', models.FloatField(null=True)),
                ('athena_queries_executed', models.JSONField(default=list)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteration_logs', to='versions.version')),
            ],
            options={
                'db_table': 'version_iteration_logs',
                'ordering': ['iteration_number'],
            },
        ),
    ]
