# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('step_number', models.PositiveIntegerField(verbose_name='Número do Step')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Step')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('WAITING', 'Aguardando'), ('ACTIVE', 'Ativo'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('SKIPPED', 'Pulado')], default='WAITING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Step de Aprovação',
                'verbose_name_plural': 'Steps de Aprovação',
                'db_table': 'approval_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Progresso'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='Passo Atual')),
                ('total_steps', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas Gerais')),
            ],
            options={
                'verbose_name': 'Workflow de Aprovação',
                'verbose_name_plural': 'Workflows de Aprovação',
                'db_table': 'approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
    ]
