# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='versions.version', verbose_name='Versão'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_steps', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalworkflow', verbose_name='Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'step_number')},
        ),
    ]
