# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='main', max_length=255)),
                ('terraform_files', models.JSONField(default=dict, verbose_name='Arquivos Terraform')),
                ('estimated_resources', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infra_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerraformPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Aguardando Revisão'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('APPLYING', 'Aplicando'), ('APPLIED', 'Aplicado'), ('FAILED', 'Falhou')], default='PENDING_REVIEW', max_length=20)),
                ('plan_output', models.TextField(blank=True, verbose_name='Output do Plan')),
                ('resources_to_add', models.IntegerField(default=0)),
                ('resources_to_change', models.IntegerField(default=0)),
                ('resources_to_destroy', models.IntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'terraform_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
