# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_terraform_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terraformplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terraformplan',
            name='infra_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_plans', to='infra.infraconfig'),
        ),
        migrations.AddField(
            model_name='infraconfig',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_infra_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infraconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infraconfig',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_configs', to='projects.project'),
        ),
    ]
