# Generated by Django 4.2.16 on 2026-04-03 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Ação')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo do Recurso')),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID do Recurso')),
                ('payload', models.JSONField(default=dict, help_text='Dados completos do evento', verbose_name='Payload')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'db_table': 'audit_events',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
