# Generated by Django 4.2.16 on 2026-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True, help_text='ID para agrupar passos de uma mesma execução')),
                ('job_type', models.CharField(db_index=True, max_length=50)),
                ('step_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0, help_text='Duração da etapa em milissegundos')),
                ('input_tokens', models.IntegerField(default=0, help_text='Tokens enviados (se IA)')),
                ('output_tokens', models.IntegerField(default=0, help_text='Tokens recebidos (se IA)')),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Trace de Execução',
                'verbose_name_plural': 'Traces de Execução',
                'db_table': 'audit_execution_traces',
                'ordering': ['timestamp'],
            },
        ),
    ]
